name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: ap-northeast-2
      CLUSTER_NAME: pablorouan-eks-lab
      ECR_REGISTRY: docker.io/prouan  # You’re using Docker Hub, not ECR

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Install kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'latest'

    - name: Install eksctl
      run: |
        curl --silent --location "https://github.com/weaveworks/eksctl/releases/latest/download/eksctl_$(uname -s)_amd64.tar.gz" | tar xz -C /tmp
        sudo mv /tmp/eksctl /usr/local/bin

    - name: Update kubeconfig
      run: eksctl utils write-kubeconfig --cluster $CLUSTER_NAME --region $AWS_REGION

    - name: Build and Push vote image
      run: |
        docker build -t $ECR_REGISTRY/vote:latest ./vote
        docker push $ECR_REGISTRY/vote:latest

    - name: Build and Push result image
      run: |
        docker build -t $ECR_REGISTRY/result:latest ./result
        docker push $ECR_REGISTRY/result:latest

    - name: Build and Push worker image
      run: |
        docker build -t $ECR_REGISTRY/worker:latest ./worker
        docker push $ECR_REGISTRY/worker:latest

    - name: Deploy to EKS
      run: |
        kubectl apply -f K8s/
        kubectl rollout restart deployment vote -n voting-app
        kubectl rollout restart deployment result -n voting-app
        kubectl rollout restart deployment worker -n voting-app
